export const strings = {
  en: {
    title: 'Mark the spot',
    station: 'Capital Bikeshare station',
    corral: 'Bike and scooter parking corral',
    taglineStation: 'Know a spot that needs a Capital Bikeshare station? Mark it on the map.',
    taglineCorral: 'Know a spot that needs a corral for tidier bike and scooter parking? Mark it on the map.',
    search: 'Search an Alexandria address',
    step2: 'Drop a pin',
    hintTouch: 'Move the map until the crosshair is on the spot, then drop the pin.',
    hintMouse: 'Click the map, then drag the pin to adjust.',
    drop: 'Drop a pin here',
    centre: 'Use the map centre',
    step3: 'Why here? Optional',
    submit: 'Submit suggestion',
    cancel: 'Cancel',
    privacy: 'Your dot and the count are public. Notes go to City staff only.',
    near: 'Near {address}',
    outside: 'Suggestions are for places inside the City of Alexandria.',
    added: 'Added to the map. Thank you.',
    meToo: 'Me too',
    voted: 'Thanks for your vote',
    wantsStation: '{n} people want a station here',
    wantsStationOne: '1 person wants a station here',
    wantsCorral: '{n} people want a corral here',
    wantsCorralOne: '1 person wants a corral here',
    existingStation: 'Existing station',
    existingCorral: 'Existing corral',
    suggested: 'Suggested, with count',
    locate: 'My location',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    help: 'How it works',
    helpStep1: 'Find the place with the search box, your location, or by moving the map.',
    helpStep2: 'Drop a pin and drag it to the exact spot.',
    helpStep3: 'Add a note if you like, then submit.',
    helpVote: 'Tap a dot to add your vote to a spot someone already suggested.',
    helpPrivacy: 'Your dot and the count are public. Notes go to City staff only. No names or contact details are collected.',
    helpLinks: 'Learn more:',
    dockless: 'Dockless mobility',
    close: 'Close',
    failed: 'Couldn’t send that. Try again.',
    noLocation: 'Couldn’t get your location.',
    demo: 'Demo mode: suggestions are not saved yet.',
    footer: 'City of Alexandria · Transportation and Environmental Services',
  },
  es: {
    title: 'Marque el lugar',
    station: 'Estación de Capital Bikeshare',
    corral: 'Corral para bicicletas y scooters',
    taglineStation: '¿Conoce un lugar que necesita una estación de Capital Bikeshare? Márquelo en el mapa.',
    taglineCorral: '¿Conoce un lugar que necesita un corral para estacionar bicicletas y scooters con más orden? Márquelo en el mapa.',
    search: 'Busque una dirección en Alexandria',
    step2: 'Coloque un marcador',
    hintTouch: 'Mueva el mapa hasta que la mira quede sobre el lugar y luego coloque el marcador.',
    hintMouse: 'Haga clic en el mapa y arrastre el marcador para ajustarlo.',
    drop: 'Colocar marcador aquí',
    centre: 'Usar el centro del mapa',
    step3: '¿Por qué aquí? Opcional',
    submit: 'Enviar sugerencia',
    cancel: 'Cancelar',
    privacy: 'Su punto y el conteo son públicos. Las notas solo las ve el personal de la Ciudad.',
    near: 'Cerca de {address}',
    outside: 'Las sugerencias son para lugares dentro de la Ciudad de Alexandria.',
    added: 'Añadida al mapa. Gracias.',
    meToo: 'Yo también',
    voted: 'Gracias por su voto',
    wantsStation: '{n} personas quieren una estación aquí',
    wantsStationOne: '1 persona quiere una estación aquí',
    wantsCorral: '{n} personas quieren un corral aquí',
    wantsCorralOne: '1 persona quiere un corral aquí',
    existingStation: 'Estación existente',
    existingCorral: 'Corral existente',
    suggested: 'Sugerido, con conteo',
    locate: 'Mi ubicación',
    zoomIn: 'Acercar',
    zoomOut: 'Alejar',
    help: 'Cómo funciona',
    helpStep1: 'Encuentre el lugar con el buscador, su ubicación o moviendo el mapa.',
    helpStep2: 'Coloque un marcador y arrástrelo al punto exacto.',
    helpStep3: 'Agregue una nota si lo desea y envíe la sugerencia.',
    helpVote: 'Toque un punto para sumar su voto a un lugar que alguien ya sugirió.',
    helpPrivacy: 'Su punto y el conteo son públicos. Las notas solo las ve el personal de la Ciudad. No se recopilan nombres ni datos de contacto.',
    helpLinks: 'Más información:',
    dockless: 'Scooters y bicicletas compartidas',
    close: 'Cerrar',
    failed: 'No se pudo enviar. Inténtelo de nuevo.',
    noLocation: 'No se pudo obtener su ubicación.',
    demo: 'Modo de demostración: las sugerencias todavía no se guardan.',
    footer: 'Ciudad de Alexandria · Transporte y Servicios Ambientales',
  },
};
