export const strings = {
  en: {
    name: 'English',
    title: 'Suggest a location',
    station: 'Capital Bikeshare station',
    corral: 'Bike and scooter parking corral',
    stationShort: 'Bikeshare station',
    corralShort: 'Bike and scooter corral',
    welcome: 'Show the City of Alexandria where you’d like a new Capital Bikeshare station or a corral for bike and scooter parking. Drop a pin on the map, or add your vote to a spot someone else suggested.',
    ask: 'What would you like to suggest?',
    loading: 'Loading the map…',
    choose: 'Choose a location type to continue.',
    language: 'Language',
    taglineStation: 'Know a spot that needs a Capital Bikeshare station? Mark it on the map.',
    taglineCorral: 'Know a spot that needs a corral for tidier bike and scooter parking? Mark it on the map.',
    search: 'Search an Alexandria address',
    step2: 'Drop a pin',
    hintTouch: 'Move the map until the crosshair is on the spot, then drop the pin.',
    hintMouse: 'Click the map, then drag the pin to adjust.',
    drop: 'Drop a pin here',
    centre: 'Place the pin at the map’s center',
    step3: 'Why here? Optional',
    submit: 'Submit suggestion',
    cancel: 'Cancel',
    near: 'Near {address}',
    nudgeStation: 'Someone already suggested a station close to this spot.',
    nudgeCorral: 'Someone already suggested a corral close to this spot.',
    voteThere: 'Add my vote there instead',
    sureTitle: 'Are you sure?',
    sureBody: 'There is already a suggestion close to this spot. A vote there counts the same as a new pin and keeps the map easier to read.',
    submitAnyway: 'Submit a new one anyway',
    voteAdded: 'Your vote was added. Thank you.',
    outside: 'Suggestions are for places inside the City of Alexandria.',
    added: 'Added to the map. Thank you.',
    meToo: 'Me too',
    voted: 'Thanks for your vote',
    wantsStation: '{n} people want a station here',
    wantsStationOne: '1 person wants a station here',
    wantsCorral: '{n} people want a corral here',
    wantsCorralOne: '1 person wants a corral here',
    existingStation: 'Existing station',
    existingCorral: 'Existing corral',
    suggested: 'Suggested, with count',
    locate: 'My location',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    satellite: 'Satellite view',
    mapView: 'Map view',
    help: 'How it works',
    helpStep1: 'Find the place with the search box, your location, or by moving the map.',
    helpStep2: 'Drop a pin and drag it to the exact spot.',
    helpStep3: 'Add a note if you like, then submit.',
    helpVote: 'Tap a dot to add your vote to a spot someone already suggested.',
    helpKeyboard: 'Without a mouse: search for an address, then choose “Place the pin at the map’s center.” The arrow keys move the map.',
    helpPrivacy: 'The feedback you provide is public. No names or contact details are collected.',
    helpOther: 'Can’t use the map? Send your suggestion through',
    helpLinks: 'Learn more:',
    dockless: 'Dockless mobility',
    close: 'Close',
    failed: 'Couldn’t send that. Try again.',
    limit: 'That’s the limit for today. Thank you for your suggestions.',
    noLocation: 'Couldn’t get your location.',
    demo: 'Demo mode: suggestions are not saved yet.',
    footer: 'City of Alexandria · Transportation and Environmental Services',
  },
  es: {
    name: 'Español',
    title: 'Sugiera un lugar',
    station: 'Estación de Capital Bikeshare',
    corral: 'Corral para bicis y scooters',
    stationShort: 'Estación de bicis',
    corralShort: 'Corral de bicis y scooters',
    welcome: 'Muestre a la Ciudad de Alexandria dónde le gustaría una nueva estación de Capital Bikeshare o un corral para estacionar bicis y scooters. Coloque un marcador en el mapa o sume su voto a un lugar que otra persona sugirió.',
    ask: '¿Qué le gustaría sugerir?',
    loading: 'Cargando el mapa…',
    choose: 'Elija un tipo de lugar para continuar.',
    language: 'Idioma',
    taglineStation: '¿Conoce un lugar que necesita una estación de Capital Bikeshare? Márquelo en el mapa.',
    taglineCorral: '¿Conoce un lugar que necesita un corral para estacionar bicicletas y scooters con más orden? Márquelo en el mapa.',
    search: 'Busque una dirección en Alexandria',
    step2: 'Coloque un marcador',
    hintTouch: 'Mueva el mapa hasta que la mira quede sobre el lugar y luego coloque el marcador.',
    hintMouse: 'Haga clic en el mapa y arrastre el marcador para ajustarlo.',
    drop: 'Colocar marcador aquí',
    centre: 'Colocar el marcador en el centro del mapa',
    step3: '¿Por qué aquí? Opcional',
    submit: 'Enviar sugerencia',
    cancel: 'Cancelar',
    near: 'Cerca de {address}',
    nudgeStation: 'Alguien ya sugirió una estación muy cerca de este lugar.',
    nudgeCorral: 'Alguien ya sugirió un corral muy cerca de este lugar.',
    voteThere: 'Sumar mi voto allí',
    sureTitle: '¿Está seguro?',
    sureBody: 'Ya existe una sugerencia muy cerca de este lugar. Un voto allí cuenta igual que un marcador nuevo y mantiene el mapa más claro.',
    submitAnyway: 'Enviar una nueva de todos modos',
    voteAdded: 'Su voto fue añadido. Gracias.',
    outside: 'Las sugerencias son para lugares dentro de la Ciudad de Alexandria.',
    added: 'Añadida al mapa. Gracias.',
    meToo: 'Yo también',
    voted: 'Gracias por su voto',
    wantsStation: '{n} personas quieren una estación aquí',
    wantsStationOne: '1 persona quiere una estación aquí',
    wantsCorral: '{n} personas quieren un corral aquí',
    wantsCorralOne: '1 persona quiere un corral aquí',
    existingStation: 'Estación existente',
    existingCorral: 'Corral existente',
    suggested: 'Sugerido, con conteo',
    locate: 'Mi ubicación',
    zoomIn: 'Acercar',
    zoomOut: 'Alejar',
    satellite: 'Vista satelital',
    mapView: 'Vista de mapa',
    help: 'Cómo funciona',
    helpStep1: 'Encuentre el lugar con el buscador, su ubicación o moviendo el mapa.',
    helpStep2: 'Coloque un marcador y arrástrelo al punto exacto.',
    helpStep3: 'Agregue una nota si lo desea y envíe la sugerencia.',
    helpVote: 'Toque un punto para sumar su voto a un lugar que alguien ya sugirió.',
    helpKeyboard: 'Sin ratón: busque una dirección y elija «Colocar el marcador en el centro del mapa». Las flechas del teclado mueven el mapa.',
    helpPrivacy: 'Los comentarios que usted envía son públicos. No se recopilan nombres ni datos de contacto.',
    helpOther: '¿No puede usar el mapa? Envíe su sugerencia por',
    helpLinks: 'Más información:',
    dockless: 'Scooters y bicicletas compartidas',
    close: 'Cerrar',
    failed: 'No se pudo enviar. Inténtelo de nuevo.',
    limit: 'Ese es el límite por hoy. Gracias por sus sugerencias.',
    noLocation: 'No se pudo obtener su ubicación.',
    demo: 'Modo de demostración: las sugerencias todavía no se guardan.',
    footer: 'Ciudad de Alexandria · Transporte y Servicios Ambientales',
  },
  am: {
    name: 'አማርኛ',
    title: 'ቦታ ይጠቁሙ',
    station: 'የCapital Bikeshare ጣቢያ',
    corral: 'የብስክሌትና የስኩተር ማቆሚያ',
    stationShort: 'የብስክሌት ጣቢያ',
    corralShort: 'የብስክሌትና ስኩተር ማቆሚያ',
    welcome: 'አዲስ የCapital Bikeshare ጣቢያ ወይም የብስክሌትና የስኩተር ማቆሚያ የት እንዲኖር እንደሚፈልጉ ለአሌክሳንድሪያ ከተማ ያሳዩ። በካርታው ላይ ምልክት ያስቀምጡ፣ ወይም ሌላ ሰው በጠቆመው ቦታ ላይ ድምፅዎን ይጨምሩ።',
    ask: 'ምን መጠቆም ይፈልጋሉ?',
    loading: 'ካርታው በመጫን ላይ…',
    choose: 'ለመቀጠል የቦታ ዓይነት ይምረጡ።',
    language: 'ቋንቋ',
    taglineStation: 'የCapital Bikeshare ጣቢያ የሚያስፈልገው ቦታ ያውቃሉ? በካርታው ላይ ያመልክቱ።',
    taglineCorral: 'ብስክሌቶችና ስኩተሮች በሥርዓት እንዲቆሙ ማቆሚያ የሚያስፈልገው ቦታ ያውቃሉ? በካርታው ላይ ያመልክቱ።',
    search: 'የአሌክሳንድሪያ አድራሻ ይፈልጉ',
    step2: 'ምልክት ያስቀምጡ',
    hintTouch: 'መስቀለኛ ምልክቱ በቦታው ላይ እስኪሆን ካርታውን ያንቀሳቅሱ፣ ከዚያ ምልክቱን ያስቀምጡ።',
    hintMouse: 'ካርታውን ጠቅ ያድርጉ፣ ከዚያ ለማስተካከል ምልክቱን ይጎትቱ።',
    drop: 'ምልክቱን እዚህ ያስቀምጡ',
    centre: 'ምልክቱን በካርታው መሃል ያስቀምጡ',
    step3: 'ለምን እዚህ? (አማራጭ)',
    submit: 'ጥቆማውን ይላኩ',
    cancel: 'ሰርዝ',
    near: '{address} አቅራቢያ',
    nudgeStation: 'ከዚህ ቦታ በጣም ቅርብ የሆነ ጣቢያ ቀደም ብሎ ተጠቁሟል።',
    nudgeCorral: 'ከዚህ ቦታ በጣም ቅርብ የሆነ ማቆሚያ ቀደም ብሎ ተጠቁሟል።',
    voteThere: 'ይልቁንስ ድምፄን እዚያ ጨምር',
    sureTitle: 'እርግጠኛ ነዎት?',
    sureBody: 'ከዚህ ቦታ በጣም ቅርብ የሆነ ጥቆማ አስቀድሞ አለ። እዚያ የሚሰጥ ድምፅ እንደ አዲስ ምልክት ይቆጠራል፤ ካርታውንም ለማንበብ ቀላል ያደርገዋል።',
    submitAnyway: 'ቢሆንም አዲስ ጥቆማ ላክ',
    voteAdded: 'ድምፅዎ ተጨምሯል። እናመሰግናለን።',
    outside: 'ጥቆማዎች በአሌክሳንድሪያ ከተማ ውስጥ ላሉ ቦታዎች ብቻ ናቸው።',
    added: 'በካርታው ላይ ተጨምሯል። እናመሰግናለን።',
    meToo: 'እኔም',
    voted: 'ስለ ድምፅዎ እናመሰግናለን',
    wantsStation: 'እዚህ ጣቢያ የሚፈልጉ ሰዎች ብዛት፦ {n}',
    wantsStationOne: 'እዚህ ጣቢያ የሚፈልጉ ሰዎች ብዛት፦ 1',
    wantsCorral: 'እዚህ ማቆሚያ የሚፈልጉ ሰዎች ብዛት፦ {n}',
    wantsCorralOne: 'እዚህ ማቆሚያ የሚፈልጉ ሰዎች ብዛት፦ 1',
    existingStation: 'ያለ ጣቢያ',
    existingCorral: 'ያለ ማቆሚያ',
    suggested: 'የተጠቆመ ቦታ፣ ከድምፅ ብዛት ጋር',
    locate: 'የእኔ አካባቢ',
    zoomIn: 'አቅርብ',
    zoomOut: 'አርቅ',
    satellite: 'የሳተላይት እይታ',
    mapView: 'የካርታ እይታ',
    help: 'እንዴት እንደሚሠራ',
    helpStep1: 'ቦታውን በፍለጋ፣ በአካባቢዎ ወይም ካርታውን በማንቀሳቀስ ያግኙ።',
    helpStep2: 'ምልክት ያስቀምጡና ወደ ትክክለኛው ቦታ ይጎትቱት።',
    helpStep3: 'ከፈለጉ ማስታወሻ ይጨምሩ፣ ከዚያ ይላኩ።',
    helpVote: 'ሌላ ሰው በጠቆመው ቦታ ላይ ድምፅዎን ለመጨመር ነጥቡን ይንኩ።',
    helpKeyboard: 'ያለ መዳፊት፦ አድራሻ ይፈልጉ፣ ከዚያ «ምልክቱን በካርታው መሃል ያስቀምጡ» የሚለውን ይምረጡ። የቀስት ቁልፎች ካርታውን ያንቀሳቅሳሉ።',
    helpPrivacy: 'የሚሰጡት አስተያየት ለሕዝብ ክፍት ነው። ስም ወይም የመገናኛ መረጃ አይሰበሰብም።',
    helpOther: 'ካርታውን መጠቀም አልቻሉም? ጥቆማዎን በዚህ በኩል ይላኩ፦',
    helpLinks: 'ተጨማሪ መረጃ፦',
    dockless: 'የጋራ ስኩተሮችና ብስክሌቶች',
    close: 'ዝጋ',
    failed: 'መላክ አልተቻለም። እንደገና ይሞክሩ።',
    limit: 'ለዛሬ ገደቡ ላይ ደርሰዋል። ስለ ጥቆማዎችዎ እናመሰግናለን።',
    noLocation: 'አካባቢዎን ማግኘት አልተቻለም።',
    demo: 'የሙከራ ሁነታ፦ ጥቆማዎች ገና አይቀመጡም።',
    footer: 'የአሌክሳንድሪያ ከተማ · የትራንስፖርትና የአካባቢ አገልግሎቶች',
  },
  ar: {
    name: 'العربية',
    title: 'اقترح موقعًا',
    station: 'محطة Capital Bikeshare',
    corral: 'موقف للدراجات والسكوترات',
    stationShort: 'محطة دراجات',
    corralShort: 'موقف دراجات وسكوترات',
    welcome: 'أخبر مدينة الإسكندرية أين تودّ أن ترى محطة جديدة لـ Capital Bikeshare أو موقفًا للدراجات والسكوترات. ضع علامة على الخريطة، أو أضف صوتك إلى موقع اقترحه شخص آخر.',
    ask: 'ماذا تودّ أن تقترح؟',
    loading: 'جارٍ تحميل الخريطة…',
    choose: 'اختر نوع الموقع للمتابعة.',
    language: 'اللغة',
    taglineStation: 'هل تعرف مكانًا يحتاج إلى محطة Capital Bikeshare؟ حدّده على الخريطة.',
    taglineCorral: 'هل تعرف مكانًا يحتاج إلى موقف لتنظيم وقوف الدراجات والسكوترات؟ حدّده على الخريطة.',
    search: 'ابحث عن عنوان في الإسكندرية',
    step2: 'ضع علامة',
    hintTouch: 'حرّك الخريطة حتى تصبح علامة التصويب فوق المكان، ثم ضع العلامة.',
    hintMouse: 'انقر على الخريطة، ثم اسحب العلامة لضبط موضعها.',
    drop: 'ضع العلامة هنا',
    centre: 'ضع العلامة في وسط الخريطة',
    step3: 'لماذا هنا؟ (اختياري)',
    submit: 'إرسال الاقتراح',
    cancel: 'إلغاء',
    near: 'بالقرب من {address}',
    nudgeStation: 'سبق أن اقترح أحدهم محطة قريبة جدًا من هذا المكان.',
    nudgeCorral: 'سبق أن اقترح أحدهم موقفًا قريبًا جدًا من هذا المكان.',
    voteThere: 'أضف صوتي هناك بدلًا من ذلك',
    sureTitle: 'هل أنت متأكد؟',
    sureBody: 'يوجد اقتراح قريب جدًا من هذا المكان. التصويت هناك يُحتسب مثل علامة جديدة ويجعل الخريطة أوضح.',
    submitAnyway: 'أرسل اقتراحًا جديدًا على أي حال',
    voteAdded: 'تمت إضافة صوتك. شكرًا لك.',
    outside: 'الاقتراحات مخصّصة للأماكن داخل مدينة الإسكندرية.',
    added: 'تمت الإضافة إلى الخريطة. شكرًا لك.',
    meToo: 'أنا أيضًا',
    voted: 'شكرًا على تصويتك',
    wantsStation: 'عدد المؤيدين لمحطة هنا: {n}',
    wantsStationOne: 'عدد المؤيدين لمحطة هنا: 1',
    wantsCorral: 'عدد المؤيدين لموقف هنا: {n}',
    wantsCorralOne: 'عدد المؤيدين لموقف هنا: 1',
    existingStation: 'محطة قائمة',
    existingCorral: 'موقف قائم',
    suggested: 'موقع مقترح، مع عدد الأصوات',
    locate: 'موقعي',
    zoomIn: 'تكبير',
    zoomOut: 'تصغير',
    satellite: 'عرض القمر الصناعي',
    mapView: 'عرض الخريطة',
    help: 'طريقة الاستخدام',
    helpStep1: 'اعثر على المكان باستخدام البحث أو موقعك أو بتحريك الخريطة.',
    helpStep2: 'ضع علامة واسحبها إلى المكان بالضبط.',
    helpStep3: 'أضف ملاحظة إن شئت، ثم أرسل الاقتراح.',
    helpVote: 'اضغط على نقطة لإضافة صوتك إلى موقع سبق اقتراحه.',
    helpKeyboard: 'بدون فأرة: ابحث عن عنوان ثم اختر «ضع العلامة في وسط الخريطة». مفاتيح الأسهم تحرّك الخريطة.',
    helpPrivacy: 'الملاحظات التي تقدّمها علنية. لا تُجمع أسماء أو بيانات اتصال.',
    helpOther: 'لا تستطيع استخدام الخريطة؟ أرسل اقتراحك عبر',
    helpLinks: 'لمزيد من المعلومات:',
    dockless: 'السكوترات والدراجات المشتركة',
    close: 'إغلاق',
    failed: 'تعذّر الإرسال. حاول مرة أخرى.',
    limit: 'هذا هو الحد المسموح به لليوم. شكرًا على اقتراحاتك.',
    noLocation: 'تعذّر تحديد موقعك.',
    demo: 'وضع تجريبي: لا تُحفظ الاقتراحات بعد.',
    footer: 'مدينة الإسكندرية · إدارة النقل والخدمات البيئية',
  },
};
